# Generated by Django 5.2.8 on 2025-12-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="es_colaborador",
            field=models.BooleanField(default=False),
        ),
    ]
