# Generated by Django 5.2.8 on 2025-12-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_postimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="post"),
        ),
    ]
